a1 = int(input())
a2 = int(input())
a3 = int(input())
a4 = int(input())
a5 = int(input())
a6 = int(input())
a7 = int(input())
a8 = int(input())
a9 = int(input())

lista = []
lista.append(a1)
lista.append(a2)
lista.append(a3)
lista.append(a4)
lista.append(a5)
lista.append(a6)
lista.append(a7)
lista.append(a8)
lista.append(a9)

a = max(lista)
b = lista.index(a)
print(a)
print(b+1)
